language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/BasicConnectivityTest/BasicConnectivityTest.ino
    - PLATFORMIO_CI_SRC=examples/BasicReceiver/BasicReceiver.ino
    - PLATFORMIO_CI_SRC=examples/BasicSender/BasicSender.ino
    - PLATFORMIO_CI_SRC=examples/MessagePingPong/MessagePingPong.ino
    - PLATFORMIO_CI_SRC=examples/RangingAnchor/RangingAnchor.ino
    - PLATFORMIO_CI_SRC=examples/RangingTag/RangingTag.ino
    - PLATFORMIO_CI_SRC=examples/TimestampUsageTest/TimestampUsageTest.ino

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno --board=pro8MHzatmega328 --board=pro16MHzatmega328 --board=bluepill_f103c8